### ISSUE TITLE
Divide `PnError::Other` into multiple variants with helpful error messages 

### ISSUE THREAD

**Issue by zkochan** [pnpm/pn#16]
> This must be the most unhelpful error in here. It was used only because this code was a prototype. But if you want to seriously develop this, I think one day we should divide this error variant into multiple specific error variants, such as `ManifestReadingError(io::Error)`, `ManifestParsingError(serde::Error)`, and `FindUpError(io::Error)` for example.
>
> If you don't want to deal with this right now, you can move this little suggestion of mine into a separate issue.

_Originally posted by @KSXGitHub in https://github.com/pnpm/pn/pull/15#discussion_r1225249070_

**Comment by KSXGitHub** [comment]
How did the title get so long?

**Comment by zkochan** [comment]
It is generated automatically when you create an issue from a comment.
