### ISSUE TITLE
Replace `sh` with custom script command parser

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pn#18]
## Problem

Right now, `pn` relies on POSIX `sh` to parse and execute script commands:

https://github.com/pnpm/pn/blob/87b0bc9d9bd1bae2a672c3d0149d5fe7c2aadfb6/src/main.rs#L151-L154

This approach wouldn't work on Windows.

## Suggestion

Write a custom parser, potentially with [shell-words](https://docs.rs/shell-words/1.1.0/shell_words/) under the hood. [`shell_words::split`](https://docs.rs/shell-words/1.1.0/shell_words/fn.split.html) does not expand glob pattern, but we can expand them ourselves. (Is there any other features that npm support for script commands that I haven't mentioned?)

**Comment by zkochan** [comment]
This is how pnpm and npm does it now:

https://github.com/pnpm/npm-lifecycle/blob/99ac0429025bdf1303879723d3fbd57c585ae8a1/index.js#L231-L242

**Comment by KSXGitHub** [comment]
I see. This does make writing scripts cross-platform difficult. But if the specs say so, why disagree.
