### ISSUE TITLE
Reduce syscalls caused by `println!`

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pn#41]
@zkochan recently wrote a comment: https://github.com/pnpm/pn/pull/36#discussion_r1233031880

Which makes me think: Syscalls can be slow. However, at the moment, I don't know if it is slower than copy.

Proper benchmark is needed.

**Comment by KSXGitHub** [comment]
I'm not going to write benchmark, so if anyone is interested, feel free to do so.

/cc @pnpm/rust

**Comment by KSXGitHub** [comment]
I close this because I just realize one thing: UX is more important.

The speed different would only visible on `scripts` with thousands of items. In which case, the user would prefer to see items being lazily printed out rather than wait for the full list being print simultaneously. So regardless of whether syscalls or copying is faster, only multi-syscalls offers the right UX.

**Comment by zkochan** [comment]
Writing a function that returns the function makes it easier to test the code. This way you can write a regular test but with `println` you need an e2e.

Also, if it is so hard to even do such a simple thing as concatenating a string, I don't know why is anyone using Rust.

**Comment by KSXGitHub** [comment]
> This way you can write a regular test but with `println` you need an e2e.

We can replace `println!` with `writeln!` that targets `output: &mut impl Write`.

> if it is so hard to even do such a simple thing as concatenating a string

It's not hard, it's just slow. There are zero-cost methods to join multiple `Display` objects together, but I won't apply it here because it's poor UX (as I explained in my previous comment).

**Comment by KSXGitHub** [comment]
@zkochan Is this good enough for you?

I can also isolate all side effects into one place, but that would require some refactoring.

**Comment by zkochan** [comment]
what side effects?

**Comment by KSXGitHub** [comment]
> what side effects?

`println!` and `Command`. Testing them requires e2e.
